### ISSUE TITLE
lonlat2ij_in_tile calculations seem to be wrong

### ISSUE THREAD

**Issue by AndreasSalentinig** [TUW-GEO/Equi7Grid#12]
commit code:2a9ee974159ceec5762bc637516199c73d2a4de8
Master branch v.0.0.7

**Comment by bbauerma** [comment]
this is not the latest commit. in commit code: 7e77f7ea63db2a365390aa4784703cba302833b4
this error does not appear. please confirm. if it's fine, i will make a new release

**Comment by bbauerma** [comment]
I've found the problem. With gdal version 3, the string definitions for the projection follows a different syntax (as Sebastian has found already some weeks ago.)

So it works with gdal 2, but not with gdal 3. 

I will work on the fix

**Comment by bbauerma** [comment]
today's commits in pytileproj and Equi7Grid should fix the issue. please checkout newest commit in both packages and test it. 

if successful, I make new package relaeases.

**Comment by sebhahn** [comment]
I think writing a test in the Equi7grid package would be better than doing some local testing

**Comment by bbauerma** [comment]
there are many tests in the packages covering that (pyton 2&3, gdal2&3), but, as we've seen in this case, the local environment, the gdal version, the python version, who-knows-what-else, can impact here...

Andreas - please test it for your environment.

**Comment by sebhahn** [comment]
Andreas can provide a test case where it fails?
