### ISSUE TITLE
mixup in doc of "tile.xy2ij" and "tile.ij2xy"

### ISSUE THREAD

**Issue by raphaelquast** [TUW-GEO/Equi7Grid#17]
@bbauerma 
there's some mixup in the documentation of the tile-functions `tile.xy2ij` and `tile.ij2xy`

- the doc of `tile.xy2ij` says it returns               **(COLUMN, ROW)**
- the doc of `tile.ij2xy` says its arguments are  **(ROW, COLUMN)**
   (I guess this is wrong...)

...if the docs would be correct, this should not be true:

```python
from equi7grid import equi7grid
grid = equi7grid.Equi7Grid(500)
tile = grid.create_tile('EU500M_E048N012T6')
(4873500, 1233000) == tile.ij2xy(*tile.xy2ij(4873500, 1233000))
>>> True
```

**Comment by bbauerma** [comment]
is merged and closed now, with [this commit in pytileproj](https://github.com/TUW-GEO/pytileproj/commit/5e6ecd1df73f2a495f43c7d01ffadba99ee7abe9)

however, I changed the defaul to "ul", instead of "center"!
