### ISSUE TITLE
setuptools>=65.0.0 not compatible?!

### ISSUE THREAD

**Issue by bbauerma** [TUW-GEO/Equi7Grid#26]

**Comment by SwamyDev** [comment]
I think this died with pyscaffold, I can install it with `setuptools-69.1.0` no problem:
```bash
python3 -m venv /tmp/venv
source /tmp/venv/bin/activate
pip install -e .
```
@bbauerma maybe you can confirm this on your end as well before we close it.

**Comment by bbauerma** [comment]
I just tried with a fresh environment on linux, as suggested above, and I get the following error

`ERROR: Failed building wheel for cartopy`
`ERROR: Could not build wheels for cartopy which use PEP 517 and cannot be installed directly
`

**Comment by bbauerma** [comment]
I tested new the installation instructions for Windows, and it succeeded, including all tests.
