### ISSUE TITLE
The question of the range of decibels(dB)values

### ISSUE THREAD

**Issue by cumtwu** [TUW-GEO/Equi7Grid#41]
I download S1GBM_VV_mean_mosaic_v1_EQUI7_AS010M file. and take some area in china to view.
I find that the range of dB values  seems not right. 
As my personal understand, the SAR general situation is that the dB value should be around -5 to -17. 
The distribution of results I looked at in the documentation(The normalised Sentinel-1 Global Backscatter Model, mapping Earth’s land surface with C-band microwaves.pdf) had the same distribution of values
But I noticed from the downloaded File that the dB values range around -100. 
How to solve this please, thank you!
![info123](https://github.com/TUW-GEO/Equi7Grid/assets/25859533/0575384a-c06b-47d8-ba24-94c61e60f83b)

**Comment by bbauerma** [comment]
I replied to this within the dedicated email, which was received on the same date.
