### ISSUE TITLE
migrate package to pyscaffold>=3.0

### ISSUE THREAD

**Issue by bbauerma** [TUW-GEO/Equi7Grid#7]

**Comment by mazweg** [comment]
According to [https://pyscaffold.org](url) Python2 is currently not working under PyScaffold 3: 

> Currently PyScaffold 3.0 needs at least Python 3.4 due to a bug in setuptools that only affects Python 2. For the time being use PyScaffold 2.5.* for Python 2.7 instead.

Therefore I upgraded to the latest PyScaffold 2 version (2.5.11). --> PR: https://github.com/TUW-GEO/Equi7Grid/pull/8

It should not be a problem importing a PyScaffold 2 package into a PyScaffold 3 package.

**Comment by sebhahn** [comment]
Closed with PR https://github.com/TUW-GEO/Equi7Grid/pull/8
