### ISSUE TITLE
The projection WKT files seem to be incomplete

### ISSUE THREAD

**Issue by jankovicgd** [TUW-GEO/Equi7Grid#9]
I am working with the EQUI7 grid and the defined Azimuthal_Equidistant projection and seem to be unable to fully transform coordinates properly. I have traced the error back and found that it is unable to convert the file from WKT to PROJ4.

The following code works with input a) but not b). b) seems to be defined here in the project but is missing AXIS and AUTHORITY info from a).
```
from osgeo import osr

srs = osr.SpatialReference()
srs.ImportFromWkt(PROJ)
print(srs.ExportToProj4())
```
a)
```
PROJ = 'PROJCS["Azimuthal_Equidistant",GEOGCS["WGS 84",DATUM["World Geodetic System 1984",SPHEROID["WGS 84", 6378137.0, 298.257223563, AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich", 0.0, AUTHORITY["EPSG","8901"]],UNIT["degree", 0.017453292519943295],AXIS["Geodetic longitude", EAST],AXIS["Geodetic latitude", NORTH],AUTHORITY["EPSG","4326"]],PROJECTION["Azimuthal_Equidistant"],PARAMETER["longitude_of_center", 24.0],PARAMETER["latitude_of_center", 53.0],PARAMETER["false_easting", 5837287.81977],PARAMETER["false_northing", 2121415.69617],UNIT["m", 1.0],AXIS["Easting", EAST],AXIS["Northing", NORTH]]'
```
b)
```
PROJ = 'PROJCS["Azimuthal_Equidistant",GEOGCS["GCS_WGS_1984",DATUM["D_WGS_1984", SPHEROID["WGS_1984",6378137.0,298.257223563]],PRIMEM["Greenwich ",0.0],UNIT["Degree",0.017453292519943295]],PROJECTION[" Azimuthal_Equidistant"],PARAMETER["false_easting",6988408.5356], PARAMETER["false_northing",7654884.53733],PARAMETER[" central_meridian",131.5],PARAMETER["latitude_of_origin",-19.5],UNIT ["Meter",1.0]]'
```

I get the following error with b)
```
ERROR 6: No translation for  Azimuthal_Equidistant to PROJ.4 format is known.
```

The original code is below that caused me the issue

```
from osgeo import osr

def get_geog_coords(geo_points, spatial_ref):
    t = osr.CoordinateTransformation(spatial_ref.CloneGeogCS(), spatial_ref)
    print(t)

    def transform(p):
        x, y, z = t.TransformPoint(p['lat'], p['lon'])
        return {'x': x, 'y': y}

    return {key: transform(p) for key, p in geo_points.items()}

points = {
    'll': {'lat': 47.483612, 'lon': 14.965127},
    'lr': {'lat': 47.483612, 'lon': 18.886929},
    'ul': {'lat': 49.559105, 'lon': 14.965127},
    'ur': {'lat': 49.559105, 'lon': 18.886929}
}

spatial_ref = osr.SpatialReference()
# PROJ is from b) and gathered from the metadatabase @ csw.eodc.eu
spatial_ref.ImportFromWkt(PROJ)

get_geog_coords(points, spatial_ref)

```

**Comment by jankovicgd** [comment]
It seems the issue was in the space after commas eg.
```
, PARAMETER["false_northing",7654884.53733]
", SPHEROID["WGS_1984",6378137.0,298.257223563]],
```

**Comment by bbauerma** [comment]
Hi there!
thanks for the research on the missing AXIS and AUTHORITY keywords. We'll integrate it also in the .prj files here in this project. 

However, I'm confused with your a) and b) examples, as they describe different subgrids/continents (Europe vs. South America). Can you show me what the "CSW service" is?

Two suggestions:
1) Could you test the WKTs defined here in the docu (on page 10) at 
[https://github.com/TUW-GEO/Equi7Grid/blob/master/docs/doc_files/EQUI7_V13_grid_and_tiling_definition_document_issue05.pdf](url)

2) Why not using our functions from this package here, like .xytlonlat()? That should do your job, right?
See examples in the tests at:
[https://github.com/TUW-GEO/Equi7Grid/blob/master/tests/test_equi7grid.py](url)
